### ISSUE TITLE
Alexa stopped sending notifications to magic mirror

### ISSUE THREAD

**Issue by elnathanau1** [JosefJantzen/MMM-AlexaControl#1]
Was working well previously, but found it today where Alexa would respond "Ok" when I would try to turn the page, but magic mirror doesn't acknowledge that it got a notification from Alexa.

**Comment by elnathanau1** [comment]
Just tried deleting all the devices and discovering devices again - only stop pm2 was found.

**Comment by JosefJantzen** [comment]
Have you discovered a second time and restart the mirror? Also the WiFi could be a problem. Is had the Problem that Alexa was in the 5 GHz WiFi and my Pi in the 2.4 GHz WiFi. Disable one of them when you discover. I hope it works then. Maybe your used Alexa Generation didn't work. Which do you use? I hope that works for you
