### ISSUE TITLE
device name fails to match 

### ISSUE THREAD

**Issue by sdetweil** [JosefJantzen/MMM-AlexaControl#13]
I have multiple MM devices, thruout my house... so I want to be able to control them separately..
i have changed the node_helper to add the device name in front of each of the menu_device creations..

so that for example I have 
```
modulename.js 
      "stop": this.translate("STOP"), "deviceName":this.translate(this.config.deviceName)
node_helper.js
       if(this.config.monitorToggle){ 
        	console.log("monitorToggle requested")
            device = {}
            device.name = _this.translations["deviceName"]+" "+_this.translations["monitor"]
//      'office monitor'
            device.port = _this.config.startPort
```
alexa device list shows (alexa.amazon.com)
office monitor   Wemo Plug	Forget

'office restart'
etc

the device discovery works and each of the devices is shown with the  two part name
i also have an existing device (an temp sensor for my thermostat) which is named 'Office'

when I say ' Alexa turn off office monitor', i get 'office doesn't support that'
so somehow the full name is not being searched.

the fauxmo  example shows multi-word device names 'Fake device 1"

I had also created a custom device called 'Office'
```
devices: {
	            devices: [{
			        name: 'Office',
			        port: 11100,
			        handler: 'console.log("office device invoked, action="+action)'
			    }  
			    ]
}
```
and it received the action notification from fauxmo, when I said 'alexa turn off office' or alexa 'turn off office monitor'
i have deleted that device (alexa forget device)

am I doing something wrong?

**Comment by sdetweil** [comment]
i deleted my 'Office' thermostat device, and now 'alexa turn off office monitor' works..
I created node-fauxmo issue 1
https://github.com/lspiehler/node-fauxmo/issues/1

**Comment by JosefJantzen** [comment]
Hi. I answered you in the other issue. Is the Office thermostat device a "real" device. Maybe it usee the same port. And if you would like to run more then one mirror in your home you have to set different start ports for each of them but not one at 11000 and the other on 11001. Set one to 11000 and another to 13000 and so on.

**Comment by sdetweil** [comment]
>Is the Office thermostat device a "real" device.

yes, real device

switching to port range 13000 doesn't help..  still get office doesn't support that

works ok for on, not ok for off 'office doesn't support that' for 'alexa turn off office monitor'

**Comment by sdetweil** [comment]
@JoChef2  thanks for the info on different port ranges on different systems on same network.. 

got to make 1st system work.. then on to others...

**Comment by sdetweil** [comment]
by changing the original physical device name, and the AlexaControl virtual device names, the collision is gone... see my pull request
