### ISSUE TITLE
Little confusion

### ISSUE THREAD

**Issue by airart** [JosefJantzen/MMM-AlexaControl#16]
Hi , i don't understand how change page in my MM , i've already installed your module and mmm-page-indicator , my echo input turn on and off tv with "alexa accendi monitor " or "alexa spegni monitor " but how change pages ? and how i can change device name .? . "monitor" is so lame 

thank u so much

**Comment by JosefJantzen** [comment]
Hi, first you have to install [MMM-pages](https://github.com/edward-shen/MMM-pages).

**Comment by airart** [comment]
i forgot to tell , i've already install mmm-pages ;-)

**Comment by JosefJantzen** [comment]
Have you set the number of pages you want in the config?

**Comment by airart** [comment]
yes i do

**Comment by JosefJantzen** [comment]
Have Alexa discoverd the devices for the pages? If she has you can say "Alexa turn on Page 2". The names can you change in the Alexa app.

**Comment by airart** [comment]
alexa cannot find the peripheral page, only monitor, refesh, restart pm2, stop pm2

**Comment by JosefJantzen** [comment]
Ok. If you have configure is like this with your number of pages it should work:
````js
modules:[
    {
        module: 'MMM-AlexaControl',
        position: 'middle_center',
        config:{
            pm2ProcessName: "mm",
            vcgencmd: "vcgencmd",
            pages: 3
        }
    }
]
````
So have you made any network changes? That could be a problem. Sometimes it help's when you restart your Alexa.

**Comment by airart** [comment]
No network change 
This is the code

{
			module: 'MMM-AlexaControl',
			position: 'bottom_bar',
			config:{
				image: false,
				pm2ProcessName: "mm",
				vcgencmd: "vcgencmd",
				deviceName: "specchio",
				page: 3
				}
		},
		{
			module: 'MMM-page-indicator',
			position: 'bottom_bar',
			config: {
				pages: 3,
				activeBright: true,
			}
		},

I' ve not install PM2 , maybe this is the problem .... or not..

**Comment by JosefJantzen** [comment]
No that's not the problem. You set the option`page` and not `pages`. I think that's the problem.

**Comment by airart** [comment]
it's woooork !!!!!! i love you 
I had lost the s!   fuck, I was looking at spaces and commas .... lol
This form is cool
