### ISSUE TITLE
Translation files not being used

### ISSUE THREAD

**Issue by jsabin** [JosefJantzen/MMM-AlexaControl#17]
Based on changing values in the files and looking at the code, it doesn't appear that the translation files are being used (ie. en.json and de.json). 

The getTranslations() function is not being called.

**Comment by JosefJantzen** [comment]
Hi, the getTranslations() function is called in line 31 in MMM-AlexaControl.js. But the translation files aren't very important. That's only the device names. But you can change them in the Alexa app. So I don't really understand where your problem is.

**Comment by jsabin** [comment]
I didn't realize you can change the names on Alexa.  I set that getTranslations is defined on line 31 but I don't see it getting called anywhere. But as you say it's not that big of a deal if I can change names in Alexa.
