### ISSUE TITLE
works with google home?

### ISSUE THREAD

**Issue by sgarg15** [JosefJantzen/MMM-AlexaControl#18]
@JoChef2 Will this module work with google home mini?

**Comment by JosefJantzen** [comment]
Hi, I don't know if  it works with a google home mini because I don't have one. But I think the wemos devices I emulate should work with a google home. So test it. You could use the default config and test the preconfigured devices. Let me Know if it works.

**Comment by J0han3s** [comment]
> Hi, I don't know if it works with a google home mini because I don't have one. But I think the wemos devices I emulate should work with a google home. So test it. You could use the default config and test the preconfigured devices. Let me Know if it works.

Any luck with this?

**Comment by soubhik-khan** [comment]
I tried with my google home, it didn't detect the device. Also it broke the MMM-Sreencast module while this module was installed. I coudn't find raspberrypi as a cast device from Youtube. After removing this module, I could see the cast option again. It will be really great to have a module which will work with google home! :)
