### ISSUE TITLE
Thanks you for your great work ! 

### ISSUE THREAD

**Issue by pandeyprakhar00** [JosefJantzen/MMM-AlexaControl#19]
@JoChef2 

Thank you for building this module, which allowed me to build my own version of Magic Mirror !

https://www.youtube.com/watch?v=sCetiJk2Qus&list=PLBy3Sw0lBrNeihCn0fOr-m5RYJNb4w4IS

🥇

**Comment by JosefJantzen** [comment]
Thanks. I'm happy that it works for you well.
