### ISSUE TITLE
Uncaught error exception

### ISSUE THREAD

**Issue by alexlobrano** [JosefJantzen/MMM-AlexaControl#2]
I'm getting an uncaught error exception in the node_helper.js file. It happens at line 97, `counter = 0 + Object.keys(menuD.devices).length` in the menuDevices function. I tried to get around it by commenting out line 28 (where menuDevices is called in setDevices) and then changing line 32 to `fauxMoPages = new FauxMo(pD);` , but that gave me an uncaught error exception on line 32 instead. Not sure what's happening, any help would be appreciated. I used your example in my configuration file, do I need to add anything to this: 

```
modules:[
    {
        module: 'MMM-AlexaControl',
        position: 'middle_center',
        config:{
            image: true,
            pm2ProcessName: "mm",
            vcgencmd: true,
        }
    }
]
```

**Comment by JosefJantzen** [comment]
I have made a mistake. Because of that my example config didn't work.  Now it works. To update it navigate to the `MMM-AlexaControl` folder and run the command `git pull`. Then it should work.
