### ISSUE TITLE
Alexa doesn't find new devices

### ISSUE THREAD

**Issue by neilkappel** [JosefJantzen/MMM-AlexaControl#20]
hello, my Alexa device is the same raspberry pi which i use for the smart mirror.
Obviously the smart mirror and the Alexa are on the same WiFi.
My configuration on the mirror's config.js file is as foolows:
{
                        module: 'MMM-AlexaControl',
			position: 'middle_center',
			config:{
			    image: false,
			    pm2ProcessName: "mm",
			    vcgencmd: "vcgencmd",
			}
},
When I turn on the mirror and ask Alexa to find new device I get an answers that no new device was found.
Please help!
Thanks in advance.

**Comment by cowboysdude** [comment]
Did you try? 

Devices not found:

Make sure that your Alexa and Pi are in the same Wifi. I had also the problem that my Pi was in the 2.4GHz Wifi and my Alexa in the 5GHz Wifi. It's only a problem when you discover the devices. To solve the problem disable one of the Wifis for a moment or turn the Wifi on your Pi on and off till it works.

Have you used the port before? Try every devices from the mirror. Probably the name is wrong. If that happen delete the device and discover for new devices. Define yourself ports for notification and custom devices to prevent this problem.

Wrong action happen:

You used the Port before. To solve the problem delete old devices and define a custom port for the device if it's a notification or custom device.

Just asking :)

**Comment by neilkappel** [comment]
Hello, 
I don't have a dedicated Alexa device.
My Alexa is running on the same raspberry pi that is running the mirror, therefore the mirror and Alexa for sure use the same WiFi.

I don't know what is the meaning of using the port but I guess that the answer is yes as I have installed MMM-remote-control and was able to control the modules in the mirror from my pc.

**Comment by cowboysdude** [comment]
That's great is running on the 2.4Ghz frequency?  Running it on a 5Ghz it won't work.

**Comment by neilkappel** [comment]
Yes, the raspberry pi is connected to a 2.4GHz WiFi network.

**Comment by JosefJantzen** [comment]
Hi,
@cowboysdude I think that these steps don't help because the Mirror and Alexa are on the same Pi. @neilkappel I think the problem is that Alexa doesn't search for devices on her own device because that's normally not the case.  I haven't tested it but I think it didn't work. So I think you have to use another module with voice recognition or you need a second device. I haven't tested my module with Alexa on another Pi but I think that should work.

**Comment by neilkappel** [comment]
@JoChef2 I have also tried to find new device from the Alexa at my phone and didn't succeed.

**Comment by JosefJantzen** [comment]
If I search on my phone my echo dot blinks anyway. So I think my module doesn't work in this configuration.
