### ISSUE TITLE
Multiple notifications triggers in Notification Device

### ISSUE THREAD

**Issue by WaltmanBeta** [JosefJantzen/MMM-AlexaControl#21]
I am really looking for some help (maybe a feature add if it can't be done with the code as written). I am using MMM-pages, MMM-page-indicator and MMM-CalendarExt2. Using CalendarExt2 the user can setup multiple scenes to allow different configurations but i am having issues as I am looking to change to page 2 of MMM-pages (where I have setup a full screen month view using a second scene for CalendarExt2). I should be able to display everything the way I want if I am able to send a few notifications. I figured I could use the notifications config to allow multiple commands to be sent at once but I have not been able to do such thus far.

ANY help to get this working would be greatly appreciated.

The two notification i am trying to send in one "Notification Device" is as follows:

- sendNotification("CALEXT2_SCENE_NEXT", "sceneNext")
- sendNotification("PAGE_INCREMENT")

I am able to run one at a time but not together in a single notification device and yes I am able to interact with the device with Alexa.

Section i am having issue with:
```
notifications: [
					{
						name: 'Month View',
						port: 11101,
						OnOff: false,
					notification: ["CALEXT2_SCENE_NEXT", "sceneNext"]
					}
				],
```

**Comment by JosefJantzen** [comment]
Hi, for that what you want you don't need two notifications. First you have to do some things so CalendarExt2 works with MMM-Pages. I'm not sure if you have done this. That's the [wiki page](https://github.com/eouia/MMM-CalendarExt2/wiki/Tip:-Sync-with-MMM-Pages.) you need. When you done that you don't need two devices anymore. You can use the page devices or a notification device with the "PAGE_INCREMENT" notification now.
 Today I added a [wiki](https://github.com/JoChef2/MMM-AlexaControl/wiki) to my repo with better explanations. [Your problem](https://github.com/JoChef2/MMM-AlexaControl/wiki/Other-modules#mmm-pages-with-mmm-calendarext2) is also part of it. If you want to use the "PAGE_INCREMENT" notification you could look [here](https://github.com/JoChef2/MMM-AlexaControl/wiki/Other-modules#mmm-pages). Make sure you edit the port.
I'm not sure if I get your problem. Tell me if I was wrong.

**Comment by WaltmanBeta** [comment]
Thank you SO much! The wiki is a really nice add! It helped explain the configuration well while also clearing up some of the confusion that I had while setting up the module (which I stumbled through). That being said I was also able to get it working using MMM-NotificationTrigger (about 4 hours ago) so that if/when I add more pages to the display I am able to have some without CalendarExt2 displayed. I will have to look into this solution as to broaden my understanding and help in the future. Again thank you so much.
