### ISSUE TITLE
Alexa Connection

### ISSUE THREAD

**Issue by nasianboi** [JosefJantzen/MMM-AlexaControl#22]
Hi!

So when I installed this onto my Smart Mirror, it worked perfectly fine the first time. I was able to connect my Echo Dot and tell my Alexa to play music on Spotify and it pulled up my Spotify module onto the mirror. However, when I restarted the Magic Mirror to install another module or to test my the MagicMirror capabilities, the Alexa doesn't seem to pull up my spotify module anymore. 

I did reinstall the module to see if I could fix the issue, and the same thing happened. I would work on initial installation but upon restarting, the Alexa wouldn't interact with the other modules installed. Is there anything I can do, or does anyone know how I can fix this?

I also have my Magic Mirror to start on boot through an executable script.

**Comment by JosefJantzen** [comment]
Hi,
I'm not sure why this happens. Can you please post your config. Maybe there is something wrong.
