### ISSUE TITLE
Need Help add MMM-Volume Notification commands

### ISSUE THREAD

**Issue by hm1234** [JosefJantzen/MMM-AlexaControl#25]
I have added both MMM-AlexaControl and MMM-Volume and I want to add a notification for volume up and volume down. I have added a notification into the config file however I am unable get the device to show up inside my alexa app. I wanted to know how I could trigger it.

Here is my config code
`  {
        module: 'MMM-AlexaControl',
        //position: 'bottom_right',
        config:{
            startPort: 11100,
            image: true,
            pm2ProcessName: "MagicMirror",
            vcgencmd: "vcgencmd",
            pages: 3,
            notifications: [
                {
                    name: 'Volume UP',
                    port: 11100,
                    OnOff: false,
                    notification: ["VOLUME_UP", "null"]
                },
                {
                    name: 'Volume Down',
                    port: 11101,
                    OnOff: false,
                    notification: ["VOLUME_DOWN", "null"]
                }
            ],
            }
        },`

Here is the notification commands for MMM-Volume
`
    notifications: {
      VOLUME_GET : "VOLUME_GET",
      VOLUME_SET : "VOLUME_SET",
      VOLUME_UP : "VOLUME_UP",
      VOLUME_DOWN: "VOLUME_DOWN",
      VOLUME_STORE : "VOLUME_STORE",
      VOLUME_RESTORE : "VOLUME_RESTORE",
      VOLUME_TOGGLE : "VOLUME_TOGGLE",
      CURRENT_VOLUME : "CURRENT_VOLUME",`

![image](https://user-images.githubusercontent.com/13208530/83959786-575fcb80-a84f-11ea-967a-cab3d0e43dd8.png)

https://github.com/Anonym-tsk/MMM-Volume

**Comment by masonbesmer** [comment]
pls help dev by using pastebin for config as github doesn't show formatting and it could be a formatting error.

**Comment by hm1234** [comment]
@shotbyapony Here is my config file: https://pastebin.com/AzFSVjFi
This is a picture of the MMM-Volume notification commands. The github link is in my original post.
![image](https://user-images.githubusercontent.com/13208530/83960019-08fffc00-a852-11ea-95d0-8a6b5298453d.png)

**Comment by JosefJantzen** [comment]
Hi, I not sure why it doesn't work. Am I right that Alexa can't find the devices? Have you discovered other devices yet or have or had you devices with the same ports. Maybe you have to delete them in the Alexa App.

**Comment by hm1234** [comment]
Yeah I have see the rest to the app like Monitor, pages, etc

**Comment by JosefJantzen** [comment]
That's unusual.  Have you made any network changes or changed the pi from 2,4Ghz to 5Ghz wifi? And can you find this in the log:
````bash
server is listening on 11100
server is listening on 11101
````
Sometimes for me it helps to discover 5 times or something.

**Comment by hm1234** [comment]
I'll check it out later and report back
