### ISSUE TITLE
cec-client location

### ISSUE THREAD

**Issue by sdetweil** [JosefJantzen/MMM-AlexaControl#27]
in some update the vgencmd for hide was changed to cec-client

i don't find that command anywhere on any of my mirror systems.

the code says  
 if vgencmd == 'cec', then do the cec-client
else if vgencmd == 'hide' do the sleepwake thing

so I think the doc is wrong, but I don't know what cec-client is

**Comment by JosefJantzen** [comment]
Sorry. I accidentally deleted the 'hide' when I added the option cec-client in the Readme. I think you mean that. <br>
cec-client is also a possibility to control your monitor. Somebody [asked](https://github.com/JoChef2/MMM-AlexaControl/issues/23) for it.

**Comment by sdetweil** [comment]
no problem. I couldn't tell what the objective was, as the test in node_helper was 'cec' not 'cec-client' that the readme implies.

**Comment by JosefJantzen** [comment]
Thanks. I changed it in the node_helper to `cec-client` like in the docs.
