### ISSUE TITLE
does not support that?

### ISSUE THREAD

**Issue by Aerius95** [JosefJantzen/MMM-AlexaControl#28]
My device was recognized and added to Alexa devices but when i say "Alexa, turn on mirror" the response i get is "mirror does not support that". Any recommendations?

**Comment by JosefJantzen** [comment]
Hi, whats your mirror device? Have you tested other devices? I asked because it's necessary that the mirror runs to control anything. So if the mirror isn't running it's not possible to control anything. It's with my module impossible to start your mirror.
