### ISSUE TITLE
Amazon No Response

### ISSUE THREAD

**Issue by Lugenixx** [JosefJantzen/MMM-AlexaControl#29]
Hi,

Firstly, my Alexa app has found the Magic Mirror and the device works in regards to that side.

However whenever I try to say "Alexa" into my mirror there is no reply, any idea why?

**Comment by JosefJantzen** [comment]
Have you tried to discover the devices again? Otherwise I don't really have an idea.

**Comment by Lugenixx** [comment]
Will give it another go, I have a spare echo dot as it is 2nd Gen, but would have been nice to implement alexa into the mirror itself, does this module work with telling amazon to play spotify on the mirror or does it play elsewhere?

**Comment by JosefJantzen** [comment]
Am I right that you want to built your 2nd Gen into your Mirror? It is possible with my module to send notifications to the MMM-Spotify module. I don't use it so I'm not sure if it does what you want

**Comment by Lugenixx** [comment]
Does your module allow me to control other Spotify eg: "Alexa, play spotify on Mirror" - if "Mirror" was the 2nd Gen dot, would it play spotify through that.

**Comment by JosefJantzen** [comment]
I think you don't need my module for that. You could say that to another Alexa and it should work, I think. But I never tested it because I have only one. Maybe I don't really understand what you want.

**Comment by Lugenixx** [comment]
My only issue is I was going to hide the alexa in the frame so im not sure if it'd pick up audio, along with that it would've been nice to see alexa respond on the main screen

**Comment by JosefJantzen** [comment]
My module only emulates smart home devices that you can turn on and off. So that's directly not possible. But if you need only a few phrases you could write a module that reacts on notifications. But you can't display Alexa's answer on the screen with my module. Maybe that's with Awesome Alexa possible. But then you have to run the Alexa on your pi.

**Comment by Lugenixx** [comment]
I've tried using Awesome Alexa and it just didn't like it, no worries, cheers anyway. You can close this.
