### ISSUE TITLE
Alexa won't find my MagicMirror

### ISSUE THREAD

**Issue by bk24z** [JosefJantzen/MMM-AlexaControl#30]
Could this be because I don't have a physical Alexa speaker (I don't have very much smart home devices) and I just use Alexa on my laptop and phone?

**Comment by JosefJantzen** [comment]
I think that's possible because I didn't tested it without a physical devices.

**Comment by J0han3s** [comment]
I have the same issue. Does Bluetooth have to be on.?

**Comment by JosefJantzen** [comment]
No. Bluetooth shouldn't be necessary.

**Comment by J0han3s** [comment]
I've restarted and tried again. It has worked now. Thank you

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by bk24z** [comment]
@gkchim Did you change anything at all to get it to work as it still won't work for me?

**Comment by bk24z** [comment]
> I think that's possible because I didn't tested it without a physical devices.

I'm not sure what is wrong then, @JoChef2 .

**Comment by J0han3s** [comment]
Unfortutaly not, didn't work last night. Tried connecting again this afternoon and it worked.

I am using an Alexa Echo dot gen 2.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by bk24z** [comment]
Not sure what is wrong, I don't have an Alexa at all and rely on my phone and laptop.
