### ISSUE TITLE
Nothing from Alexa, like I've done nothing.

### ISSUE THREAD

**Issue by Opus26** [JosefJantzen/MMM-AlexaControl#32]
Hello,

I've got problem with ''MMM-awesome-alexa'' playing Spotify: ''music and radio playback are not supported on this device''. I wrote to Spotify and I've done some research but nothing to help me. This is why I'm trying your code but surprisingly there is nothing: it's look like I didn't even install your code. 

I've fallowed your steps and I have /home/pi/MagicMirror/modules/MMM-AlexaControl and copied/paste in /home/pi/MagicMirror/config/config.js the module. The SmartMirror is running well but nothing from Alexa (no image or respond). Do I miss a step? And do you think that might arrange my problem with Spotify. Otherwise, do you have an idea what I could do for my Spotify problem :)? Thank you so much!

P.S.: the "MMM-awesome-alexa" should not create interference cause the code is // and the module not in /home/pi/MagicMirror/modules/ anymore.

Thank again!

**Comment by JosefJantzen** [comment]
Hi,
I don't think that my module can solve your problem because it only emulates smart home plugs and not a whole Alexa. If you want to use my module anyway please post your config here.
