### ISSUE TITLE
Alexa doesn't change pages

### ISSUE THREAD

**Issue by Simone7000** [JosefJantzen/MMM-AlexaControl#33]
Hello

the module works correctly but I can't change the page on the mirror even though alexa recognizes me the page command, but it has no effect on the mirror.
Consider that I have configured 2 pages.
Anyway great form thanks

**Comment by JosefJantzen** [comment]
Hi,
could you please post your config here of the module.

**Comment by Simone7000** [comment]
Thanks for your quick reply but I solved it.
I forgot to enter the page number in MMM-AlexaControl.js. Having a small screen, the page change is essential for me. Great form and great work. Congratulations and thanks again.
