### ISSUE TITLE
Turn off monitor via alexa and GPIO relay

### ISSUE THREAD

**Issue by Simone7000** [JosefJantzen/MMM-AlexaControl#34]
Hello
I would like to use your module to turn off the monitor via a relay connected to the raspberry GPIO with a notification or command via alexa.
I thought about installing the MMM-PIR-Sensor module but I can't figure out how to notify the module to activate the relay.
Is it possible to do this?
Thank you

**Comment by JosefJantzen** [comment]
Hello
the MMM-PIR-Sensor module doesn't describes it but according to the main file the monitor should wake up when you send the notification `SCREEN_WAKEUP`.  If you use that I think you should define a delay after that the monitor turns off. That should work but I can't test it.
