### ISSUE TITLE
Mehrere Magimirrors

### ISSUE THREAD

**Issue by jasimi** [JosefJantzen/MMM-AlexaControl#37]
Several Magimirrors
I have several Magicmirrors and I want Alexa to be my voice assistant everywhere.
I have successfully installed MMM-AlexaControl on a mirror and it works great.
What settings exactly do I have to make on the other mirrors so that Alexa can also find the mirrors there.
I've already given a mirror another name, but that didn't help.
I ask for your help.
Maybe you can show me an example of what to do.

**Comment by JosefJantzen** [comment]
Hi,
it's right that you want to use the `deviceName` option. It's not necessary but it's useful to identify the different devices. In addition you have to change the option `startPort`. The port identify each device in the background. The default value is 11000. Because of reserved ports for the devices you should increase this value for every new mirror with 1000. So you don't have to change this on your first mirror and set it on your second to `12000` and so on.

**Comment by jasimi** [comment]
I have two identical mirrors, each mirror has 3 sides for displaying modules. With both functions "monitor on and off", "update", "restart PM2" and "stop PM2".
What only works on a mirror is changing sides.
He can't find the pages on the other mirror. What can I do there .

**Comment by JosefJantzen** [comment]
So only the devices for the pages on your second mirror aren't working or are there more that dosen't work? Could you please send me the config of the module because with that I can't find any problems.

**Comment by jasimi** [comment]
[       {
            module: 'MMM-AlexaControl',
            position: "top_bar",
            config:{
                pm2ProcessName: "mm",
                vcgencmd: "vcgencmd",
			    pages: "3",
				startPort:"12000",
			    deviceName:"Büro"
                                }
        }

The example only works partially. The 3 Alexa commands work. What does not work is switching the pages by voice. Switching between sides works on the other mirror.

**Comment by JosefJantzen** [comment]
I think the problem is that you set the option pages to: `pages: "3"` but it has to be `pages: 3`. It's the same with  startPort.

**Comment by jasimi** [comment]
I checked everything again and suddenly everything works. Thank you for your support. Very good module. Keep it up.
