### ISSUE TITLE
Syntax of the notification part

### ISSUE THREAD

**Issue by Dimasua** [JosefJantzen/MMM-AlexaControl#38]
Hello! Can you please explain the syntax of the notification part, where I should put it in the whole MMM-AlexaControl configuration, where to put commas? I tried different options, but MM doesn't read this configuration.

**Comment by JosefJantzen** [comment]
Hi! Have I answered your question in this [issue](https://github.com/JoChef2/MMM-AlexaControl/issues/39) ?

**Comment by Dimasua** [comment]
Great, thank you!
