### ISSUE TITLE
MMM-AlexaControl with MMM-Podcast2

### ISSUE THREAD

**Issue by Dimasua** [JosefJantzen/MMM-AlexaControl#39]
Hello! I'm trying to control the MMM-Podcast2 with Alexa but can't figure out how the MMM-Podcast2 will find out that the notification configured in MMM-AlexaControl is for MMM-Podcast2? Hence can't understand where to put its notification part, whether in MMM-AlexaControl or in MMM-Podcast2 configuration array. Thank you.

**Comment by JosefJantzen** [comment]
Hi! First of all all the configurations you read in my README are for the config part of this module. So, the notifications array has to be there. I have a short explanation for MMM-Podcast2 in the Wiki [here](https://github.com/JoChef2/MMM-AlexaControl/wiki/Other-modules#mmm-podcast2). So you have to put this part in the config of this module like this: <br>
````js
{
        module: 'MMM-AlexaControl',
        position: 'middle_center',
        config:{
            image: true,
            pm2ProcessName: "mm",
            vcgencmd: "vcgencmd",
            notifications:[
                {
                    name: '<Your Name>',
                    port: 11100,
                    OnOff: false,
                    notification: ["BUTTON_PRESSED_LONG", 'payload']
                }
            ]
        }
    }
````
If you don't have more custom devices you only have to change the name. If you have other custom devices change the port to an unused.
