### ISSUE TITLE
Different devices found everytime

### ISSUE THREAD

**Issue by Dimasua** [JosefJantzen/MMM-AlexaControl#40]
Hej, when I put the Alexa into discovery mode it does not find a complete set of devices but finds always different devices, sometimes my custom devices, like "mirror podcast", and does not discover default devices, like refresh or stop. Or vice versa, only finds **some** default devices and does not discover custom devices. Here is the configuration:

module: 'MMM-AlexaControl',
        position: 'middle_center',
        config:{
            image: true,
			width: 96,
			height: 96,
			deviceName: "mirror",
            pm2ProcessName: "mm",
            vcgencmd: "vcgencmd",
			notifications:[
								{
									name: 'podcast',
									port: 11100,
									OnOff: false,
									notification: ["BUTTON_PRESSED", 'payload']
								}
						  ],
				}
		},

**Comment by JosefJantzen** [comment]
Hi, that's a problem of the nodejs module used for the Alexa part. So I can't really do something on that. I also had this issue sometimes but for me it isn't a big deal because after a few discoveries I have all devices. Your config is right.
