### ISSUE TITLE
Blackscreen

### ISSUE THREAD

**Issue by dand3l10n** [JosefJantzen/MMM-AlexaControl#41]
After installing everything the MMM won´t start properly and the whole Pi is frozen. I only see a black screen. Restarts and new installation didn´t fix it. 
Is anyone know this problem and a good workaround?

**Comment by JosefJantzen** [comment]
Hi, I don't know the problem yet. Could you please send your config and is anything in the log that could help?

**Comment by dand3l10n** [comment]
So I could fix the blackscreen by reinstall everything the third time and change ' in this " in the config. 
I still have the problem that Alexa won't find any new devices. I tried the normal bug fixes and WiFi settings already. 
My config and log: 
[MMM-alexa-config.txt](https://github.com/JoChef2/MMM-AlexaControl/files/6271153/MMM-alexa-config.txt)
[MMM-log.txt](https://github.com/JoChef2/MMM-AlexaControl/files/6271154/MMM-log.txt)

I read in a couple of forums that the fauxmojs aren't supported very well by Alexa. Some recommended using the huedo: https://github.com/mcchas/huedo instead. 
Is there a way to do this with your module?

**Comment by JosefJantzen** [comment]
In the log you can see that all module_helper are stopping. But the helper is needed for the Alexa devices. I don't know what the first error is but the second seems to be caused by the Public Transport module. If it's my module I don't know waht causes the problem because your config seems to be right. But you are right that fauxmojs isn't very well supported.  I think it should be easy to use huedo instead of it but I don't have time for that. Maybe you could do that. The part you have to change is in the node_helper file.

**Comment by dand3l10n** [comment]
The first error is from the Alexa module. The other ones came from a connection problem of the PublicTransport module. 
Could you please explain to me how to change the node_helper. I'm not good at all with java.

**Comment by dand3l10n** [comment]
I found a solution. The problem was another module named Screencast. https://github.com/kevinatown/MMM-Screencast/issues/65
I deleted this one in the config and searched again. I found everything I wanted to. 
After that, I installed Screencast again and everything works just fine.

**Comment by alexsmith1665** [comment]
Hello, I am having similar problems. I have gotten Alexa to discover my "Fake Device" per node-fauxmo instructions and can get device to listen and interact with Alexa (only turn on/off so far). But adding the module to the config leaves me with a blank screen. My device is not frozen unlike OP, but my Smart Mirror no longer displays.

This is what I have in my config file within the modules bracket:

    {
        module: 'MMM-AlexaControl',
        position: 'middle_center',
        config:{
            image: true,
            pm2ProcessName: "mm"
        }
    },

**Comment by JosefJantzen** [comment]
Hi, could you please post the log here. Maybe the problem is that you run your own instance of node-fauxmo at the same time you run the mirror on your pi, because that`s not possible and the second one will have problems also if the devices don't have the same port.

**Comment by alexsmith1665** [comment]
Hello, thank you for the reply. I actually do have two instances of node-fauxmo. One is within /home/pi/MagicMirror/node_modules/node-fauxmo and the other is within /home/pi/node_modules/node-fauxmo. Does one have better pathing over the other, and can I simply delete one of the node-fauxmo folders?

And apologizes for my noob-ness, how can I accesss my log to include it here? Thank you

**Comment by alexsmith1665** [comment]
I ended up deleting the node-fauxmo folder within /home/pi/node_modules and my MagicMirror displays now :)
