### ISSUE TITLE
Doesn't work when wifi changes

### ISSUE THREAD

**Issue by websterjazz** [JosefJantzen/MMM-AlexaControl#44]
Hi, so I installed this module and it seems to be working great on my home wifi .. I am able to refresh , switch pages ..turn on / off monitor .

But when I switched my Pi to another wifi Alexa commands no longer work .
So then I created a hotspot on my phone and created the same wifi ssid and passphrase as my home wifi . But still Alexa commands are not working . Despite even connecting my echo the new wifi hotspot.

Only when my Pi is connected to the home wifi.. This module seems to work. 
This is my config..

    
    {
        module: 'MMM-AlexaControl',
        position: 'middle_center',
        config:{
            image: true,
            vcgencmd: false,
            refresh: true,
            restart: true,
            stop: false,
            reboot: false
        }
    },

What am I missing?

**Comment by JosefJantzen** [comment]
Hi, sorry that I answer you so late. You aren't really missing something. That has nothing to do with the config. Alexa uses the IP address of the pi with a port to identify the devices in the background. So if the ip changes you have to discover the devices again. So my advice is if you really need to use the mirror in different networks, set the same static ip for the pi in all of your routers settings.
