### ISSUE TITLE
Reset discovered devices

### ISSUE THREAD

**Issue by djkemp** [JosefJantzen/MMM-AlexaControl#49]
Managed to install it easily enough and get it working first time apart from a few issues with it creating duplicate devices.

I've deleted all the devices in Alexa now but can't get it to discover them again.
Where are the devices and their connection details (ports etc) stored within this module and is there a way to reset what has been added back to an original state to make it discover the devices from scratch?

**Comment by JosefJantzen** [comment]
Hi. I'm very sorry I didn't saw your issue. I assume it's not really relevant for you now but maybe for somebody else. The used ports are the following:
````txt
pagestart:	10900
START:		11000
refresh:	11000
restartPM2:	11001
stopPM2:	11002
rebootPi:	11003
shutdownPi:	11004
monitor:	11005
usb:		11006
customstart:	11030
notifistart:	11050
commandstart:	11075
customPortStart:11100

=> 10900 - 11200
````

When you change the ports with the  `startPort` property. It's default is 11000. From the list above you can see that around that port the devices are running.
The only way to remove devices from Alexa is to delete them in the app or at the website. If you want to disable them, use the config.
If you can't discover devices after a few trys I have the sad news that the npm package I#m using is not so good and sometimes doesn't work for no reason.
