### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by PierreGode** [JosefJantzen/MMM-AlexaControl#51]
Once I installed the module and set the config, the mirror is black after restart of pm2 service. ( raspberry pi)
if i disable the module in config with /*    */ then everything works fine.

I have tried these configs

 {
        module: 'MMM-AlexaControl',
        position: 'middle_center',
        config:{
            image: true,
            pm2ProcessName: "pm2",
            vcgencmd: "vcgencmd"
  }
},

and 
 {
        module: 'MMM-AlexaControl',
        position: 'middle_center',
        config:{
            image: true,
            pm2ProcessName: "mm",
            vcgencmd: "vcgencmd"
  }
},

**Comment by JosefJantzen** [comment]
Hi. I'm very sorry I didn't saw your issue. I assume it's not really relevant for you now but maybe for somebody else. I'm no quite sure why this happens. To know more I would have needed the log of your magic mirror
