### ISSUE TITLE
Alexa doesn't discover devices

### ISSUE THREAD

**Issue by santiagos5** [JosefJantzen/MMM-AlexaControl#6]
hello,

I follow your steps, but alexa doesn't discover my device.
In my config file :

`    {
        module: 'MMM-AlexaControl',
        position: 'top left',
        config:{
            image: false,
            pm2ProcessName: "mm",
            vcgencmd: true
        }
    }`

Something wrong?

I have only 2.4ghz wifi.. Can you help me? 
I need to config devices or something else?

**Comment by JosefJantzen** [comment]
Hi,
normally you should find some devices with your config. The problem could be your Alexa. Somebody has [problems](https://forum.magicmirror.builders/topic/11568/hi-there-is-a-new-alexa-module/56?page=6) with a 1st Gen Alexa. Wich Alexa do you use? The module isn't very much tested because I only have a 3rd Gen Echo Dot. It's aa pity that you have problems and I hope we can solve them.

**Comment by santiagos5** [comment]
hi, i have only four 3rd Gen Echo Dot.. But i use discover device from my iphone, not ask to alexa..
Maybe is for that?

**Comment by JosefJantzen** [comment]
No I discover the devices from my phone too. Is in the log then you start your mirror something like this: ` server is listening on 11005` ? I think so that you discover a few times?

**Comment by santiagos5** [comment]
i have:
```
server is listening on 11000
server is listening on 11001
server is listening on 11002
server is listening on 11005
```

I tried 4-5 times.. also closing and reopening MM with pm2

**Comment by JosefJantzen** [comment]
That's all right. Have you only one 2.4Ghz Wifi and is your Pi also in the Wifi or do you use Ethernet?  That's the only ideas I still have.

**Comment by santiagos5** [comment]
only use 2.4 Ghz, 5GHz disabled, and Pi is in the Wi-Fi near the modem

**Comment by JosefJantzen** [comment]
Ok. That's bad because I don't have a idea to solve your problem.  Maybe I will find a solution. Sorry.

**Comment by santiagos5** [comment]
Ok, I'll try to remove and reinstall it, and let you know..

**Comment by JosefJantzen** [comment]
I have one idea. Does it work if you use Ethernet when you discover? Did you discover in the App for other devices without selecting a device type?

**Comment by santiagos5** [comment]
I tried with Ethernet but nothing found.. Yes I discover for other devices without selecting a device type. Now I try with switch -> other, but no devices found

**Comment by CyberRagz** [comment]
hello Joe,
I have same issue. 
I have followed all instructions .
Using Alexa app on phone. But new device (Raspberry Pi 3 B+) not detected.
On the screen Alexa icon is displayed.
Anything you can suggest please.

**Comment by rubenix** [comment]
Hello,
Im on the same situation, does not discover any device.
Had to say that worked for me before and was so happy with it, very nice work indeed!!
Started MM project from scratch. Now this module does not work for me anymore. 
uninstalled & installed the module many times with no luck at all....Any suggestions? 
stopping & starting MM from pm2 & trying to discover does not find any new one...
fauxmo issue?  logs do not tell much 'server is listening on port xxxx'
obviously im on the same net as I was before when it was working

**Comment by rubenix** [comment]
Ok, weird but needed to restart the echo device (yes, the echo device) to make new devices working; do not ask me why but its what i did and it works;
AlexaControl back to business! Thanks for this excellent work!
