### ISSUE TITLE
Commands for using this module don't work (vcgencmd, tvservice, & cec-client)

### ISSUE THREAD

**Issue by Kaliber27** [JosefJantzen/MMM-AlexaControl#62]
With my Raspi 3 B+, I found that vcgencmd, tvservice, and cec-client don't work, or at the very least not _correctly_ for whatever reason (due to one of the OS Updates disabling a GPU Driver or something along those lines.)

A work around has been to use ddcutil by replacing the vcgencmd command(s) within node_helper.js to that of `"ddcutil -d 1 setvcp D6 01"` and `"ddcutil -d 1 setvcp D6 04"` which has worked perfectly.

The problem is that now after I save the changes, it constantly wants me to update because it sees that my version is technically differing from the main module.

Any way to disable this notification or add ddcutil as one of the available options?

**Comment by JosefJantzen** [comment]
Hi, could you please provide the error message from your log? From what I understand your approach should work fine and my module does not check it's version.

**Comment by Kaliber27** [comment]
Well I feel like a fool because now it seems to be working after months of having this problem. My Apologies!
